//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetControl.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMC_BGPERIOD
    {
        public string BudgetCode { get; set; }
        public int ReviseNo { get; set; }
        public string PrjCode { get; set; }
        public string OCRCode { get; set; }
        public int Period { get; set; }
        public Nullable<decimal> PeriodAmount { get; set; }
    }
}
