//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetControl.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMC_BGTRANL
    {
        public int TRNo { get; set; }
        public int LineNum { get; set; }
        public string FromOCR { get; set; }
        public string FromPRJ { get; set; }
        public string ToOCR { get; set; }
        public string ToPRJ { get; set; }
        public Nullable<decimal> TRAmnt { get; set; }
        public string Remark { get; set; }
    }
}
