//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetControl.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMC_BGTRANH
    {
        public int TRNo { get; set; }
        public Nullable<System.DateTime> BGDate { get; set; }
        public string BudgetCode { get; set; }
        public string CreateBy { get; set; }
        public string Approve { get; set; }
        public string AppBy { get; set; }
    }
}
