//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetControl.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class HMC_BGSCENARIO
    {
        public string BudgetCode { get; set; }
        public string BudgetName { get; set; }
        public string BudgetType { get; set; }
        public string BudgetBy { get; set; }
        public string BudgetPeriod { get; set; }
        public string BudgetYear { get; set; }
        public string PeriodFrom { get; set; }
        public string PeriodTo { get; set; }
        public Nullable<int> NoOfPeriod { get; set; }
        public Nullable<int> ReviseNo { get; set; }
    }
}
