//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetControl.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPR
    {
        public int AbsEntry { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> F_RefDate { get; set; }
        public Nullable<System.DateTime> T_RefDate { get; set; }
        public Nullable<System.DateTime> F_DueDate { get; set; }
        public Nullable<System.DateTime> T_DueDate { get; set; }
        public Nullable<System.DateTime> F_TaxDate { get; set; }
        public Nullable<System.DateTime> T_TaxDate { get; set; }
        public string Free2 { get; set; }
        public string Free3 { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<int> SubNum { get; set; }
        public string Free { get; set; }
        public string Free1 { get; set; }
        public string Addition { get; set; }
        public Nullable<int> AddNum { get; set; }
        public string Category { get; set; }
        public string Indicator { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string WasStatChd { get; set; }
        public string PeriodStat { get; set; }
        public Nullable<short> UserSign2 { get; set; }
    }
}
