//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetControl.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPRJ
    {
        public string PrjCode { get; set; }
        public string PrjName { get; set; }
        public string Locked { get; set; }
        public string DataSource { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Active { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string U_HMC_UseBudget { get; set; }
        public string U_HMC_SortNo { get; set; }
        public string U_HMC_BGGroup1 { get; set; }
        public string U_HMC_BGGroup2 { get; set; }
        public Nullable<decimal> U_HMC_BudgetAmt { get; set; }
        public string U_HMC_Detail { get; set; }
    }
}
