//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetControl.Class
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NSF_DevelopEntities : DbContext
    {
        public NSF_DevelopEntities()
            : base("name=NSF_DevelopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HMC_BGTRANH> HMC_BGTRANH { get; set; }
        public virtual DbSet<HMC_BGTRANL> HMC_BGTRANL { get; set; }
        public virtual DbSet<OACP> OACP { get; set; }
        public virtual DbSet<OFPR> OFPR { get; set; }
        public virtual DbSet<OPRC> OPRC { get; set; }
        public virtual DbSet<OPRJ> OPRJ { get; set; }
        public virtual DbSet<OUSR> OUSR { get; set; }
        public virtual DbSet<HMC_BGPERIOD> HMC_BGPERIOD { get; set; }
        public virtual DbSet<HMC_BGPROJECT> HMC_BGPROJECT { get; set; }
        public virtual DbSet<HMC_BGSCENARIO> HMC_BGSCENARIO { get; set; }
        public virtual DbSet<HMC_BGSETUP> HMC_BGSETUP { get; set; }
    }
}
